[package]
name = "xi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
clap = { version = "4", features = ["derive"] }
miette = { version = "5", features = ["fancy"] }
peekmore = "1"
rug = "1"
rustyline = "11"
